name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: Python/AutoClicker/
      run: |
        python -m pip install --upgrade pip
        pip install keyboard
        pip install pyinstaller
    - name: Build
      working-directory: Python/AutoClicker/
      run: |
        pyinstaller -F -i ".\hand-click-icon-png-clip-art.ico" autoclicker.py
            
